"""Auto-generated by fcstd2b123d from /app/workspaces/pzfreo/fcd2b123d/tests/fixtures/sample_2026/HE-B-Profile_320_DIN1025-2_S235JR.FCStd."""

from build123d import (
    Align,
    BasePartObject,
    BuildLine,
    BuildSketch,
    CenterArc,
    Line,
    Mode,
    Polyline,
    RotationLike,
    extrude,
    make_face,
)


class DIN1025HEBProfile(BasePartObject):
    """Translated parametric design. Defaults match the source values."""

    def __init__(
        self,
        h: float = 320.0,
        b: float = 300.0,
        tw: float = 11.5,
        tf: float = 20.5,
        r: float = 27.0,
        length: float = 50,
        rotation: RotationLike = (0, 0, 0),
        align: Align | tuple[Align, Align, Align] | None = None,
        mode: Mode = Mode.ADD,
    ):
        with BuildSketch() as sketch:
            with BuildLine() as sketch_profile:
                (
                    Line((tw / 2, -(h / 2 - tf - r)), (tw / 2, h / 2 - tf - r))
                    + CenterArc(
                        center=(tw / 2 + r, h / 2 - tf - r),
                        radius=r,
                        start_angle=180,
                        arc_size=-90,
                    )
                    + Polyline(
                        (tw / 2 + r, h / 2 - tf),
                        (b / 2, h / 2 - tf),
                        (b / 2, h / 2),
                        (-(b / 2), h / 2),
                        (-(b / 2), h / 2 - tf),
                        (-(tw / 2 + r), h / 2 - tf),
                    )
                    + CenterArc(
                        center=(-(tw / 2 + r), h / 2 - tf - r),
                        radius=r,
                        start_angle=90,
                        arc_size=-90,
                    )
                    + Line((-(tw / 2), h / 2 - tf - r), (-(tw / 2), -(h / 2 - tf - r)))
                    + CenterArc(
                        center=(-(tw / 2 + r), -(h / 2 - tf - r)),
                        radius=r,
                        start_angle=0,
                        arc_size=-90,
                    )
                    + Polyline(
                        (-(tw / 2 + r), -(h / 2 - tf)),
                        (-(b / 2), -(h / 2 - tf)),
                        (-(b / 2), -(h / 2)),
                        (b / 2, -(h / 2)),
                        (b / 2, -(h / 2 - tf)),
                        (tw / 2 + r, -(h / 2 - tf)),
                    )
                    + CenterArc(
                        center=(tw / 2 + r, -(h / 2 - tf - r)),
                        radius=r,
                        start_angle=270,
                        arc_size=-90,
                    )
                )
            make_face()
        sketch = sketch.sketch
        he_b_profile_320_din1025_2_s235jr = extrude(sketch, amount=length)
        super().__init__(
            part=he_b_profile_320_din1025_2_s235jr,
            rotation=rotation,
            align=align,
            mode=mode,
        )


result = DIN1025HEBProfile()
