"""Auto-generated by fcstd2b123d from /app/workspaces/pzfreo/fcd2b123d/tests/fixtures/sample_2026/Flat_Bar_110x25_EN10058_S235JR.FCStd."""

from build123d import (
    Align,
    BasePartObject,
    BuildLine,
    BuildSketch,
    Mode,
    Polyline,
    RotationLike,
    extrude,
    make_face,
)


class EN10058FlatBar(BasePartObject):
    """Translated parametric design. Defaults match the source values."""

    def __init__(
        self,
        width: float = 110.0,
        thickness: float = 25.0,
        length: float = 50,
        rotation: RotationLike = (0, 0, 0),
        align: Align | tuple[Align, Align, Align] | None = None,
        mode: Mode = Mode.ADD,
    ):
        with BuildSketch() as sketch:
            with BuildLine() as sketch_profile:
                Polyline(
                    (-(width / 2), -(thickness / 2)),
                    (width / 2, -(thickness / 2)),
                    (width / 2, thickness / 2),
                    (-(width / 2), thickness / 2),
                    (-(width / 2), -(thickness / 2)),
                )
            make_face()
        sketch = sketch.sketch
        flat_bar_110x25_en10058_s235jr = extrude(sketch, amount=length)
        super().__init__(
            part=flat_bar_110x25_en10058_s235jr,
            rotation=rotation,
            align=align,
            mode=mode,
        )


result = EN10058FlatBar()
